# copyright Merzlov Nikolay merzlovnik@mail.ru

import StackMachine as SM

print("--arithmetic--")
SM.StackMachine([2, 3, "+", 4, "*", 2, "/", 6, "%", 1, "println", "-", 3, "==", "print", "print", "println"]).run()
print("--cast--")
SM.StackMachine([2, "cast_str", "println", 2.3, "cast_int", "println"]).run()
print("--dup, drop--")
SM.StackMachine([2, "println", "dup", "+", "println", "drop", "println"]).run()
print("--if_clause__")
SM.StackMachine([20, 0, 1, "if", "println"]).run()
SM.StackMachine([0, 0, 1, "if", "println"]).run()
print("--jump--")
SM.StackMachine([2, "jmp", 1, 1, "+", 10, "+", "println"]).run()
SM.StackMachine([7, "jmp", 1, 1, "+", 10, "+", "println"]).run()
print("--stack--")
SM.StackMachine([2, 3, "+", '"something_1"', '"something_2"', "stack"]).run()
print("--swap--")
SM.StackMachine([2, 3, "swap", "-", "println"]).run()
print("--read--")
SM.StackMachine(["read", "cast_int", 3, "+", "println"]).run()
print("--call, return--")
SM.StackMachine([5, "jmp", '"some_call"', "println", "return", 2, "call", 1, 2, "+", "println"]).run()
print("load, store--")
SM.StackMachine([1, '"a"', "store", "stack", '"a"', "load", 10, "+", "println"]).run()
print("--ext--")
SM.StackMachine([5, "println", "exit", 10, "println"]).run()
